apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/spring_ri_network: "true"
    io.kompose.service: discovery-service
  name: discovery-service
spec:
  containers:
  - env:
    - name: spring.cloud.config.uri
      value: http://config-service:8888
    - name: spring.main.banner-mode
      value: '"off"'
    image: thinkmicroservices/discovery-service:latest
    livenessProbe:
      exec:
        command:
        - curl
        - --fail
        - --silent
        - http://think:microservices@localhost:8761/actuator/health
      failureThreshold: 10
      periodSeconds: 30
      timeoutSeconds: 30
    name: discovery-service
    ports:
    - containerPort: 8761
    resources: {}
  restartPolicy: OnFailure
status: {}
