apiVersion: apps/v1
kind: Deployment

metadata:
  name: grafana-deployment
 
 
spec:
  replicas: 1
  selector:
    matchLabels:
      env: monitoring
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        env: monitoring
        app: grafana
    spec:
      containers:
        - name: my-grafana
          image: grafana/grafana
          volumeMounts:  
            - name: data-dir
              mountPath: /var/lib/grafana/
            
   
      
      volumes:
       - name: data-dir
         persistentVolumeClaim:
           claimName: graf-data-dir-pvc
              

 
    
