apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.service.type: clusterip
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresadmin
  name: postgresadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresadmin
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.service.type: clusterip
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/spring_ri_network: "true"
        io.kompose.service: postgresadmin
    spec:
      containers:
      - env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: user@domain.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: password
        image: dpage/pgadmin4
        imagePullPolicy: ""
        name: postgresadmin
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
