apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      env: monitoring
      app: prometheus
  template:
     metadata:
       name: prometheus
       labels:
         env: monitoring
         app: prometheus
     spec:
       containers:
         - name: my-prometheus
           image: prom/prometheus:latest
           volumeMounts:
             - name: prometheus
               mountPath: /etc/prometheus

             - name: prom-pvc
               mountPath: /etc/prometheus/data
       volumes:
         - name: prometheus
           configMap:
             name: prometheus
         - name: prom-pvc
           persistentVolumeClaim:
              claimName: prom-data-pvc
        

 
