apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.service.type: clusterip
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: sms-outbound-service
  name: sms-outbound-service
spec:
  ports:
  - name: "6020"
    port: 6020
    targetPort: 8080
  selector:
    io.kompose.service: sms-outbound-service
  type: ClusterIP
status:
  loadBalancer: {}
